version: '3.8'

services:
  
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bd_inventario
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432